nome = str(input('Digite seu nome completo: ')).strip()
print(f'Nome em maiúsculo: {nome.upper()}')
print(f'Nome em minúsculo: {nome.lower()}')
print('Quantidade de letras do seu nome: {}'.format(len(nome) - nome.count(' ')))
print('seu primeiro nome tem: {}'.format(nome.find(' ')))
